### ISSUE TITLE
Passing violation counts, fees and  request for reduction as hidden variable

### ISSUE THREAD

**Issue by jmadans** [JudicialCouncilOfCalifornia/docassemble.jcc.abilitytopay#26]

**Comment by jmadans** [comment]
Right now we are streamlining data presented to the user to simplify the experience, but we will still need for that data to be included in the final submission for the judge's to see. 

We will need to pass the following the variables in the submissions:

**Comment by rdeshpande** [comment]
This is complete, except that I don't see a place in their request API to send in the violation count. I can follow up by email.

**Comment by rdeshpande** [comment]
Confirmed from Akbar that the count is just in the description string - closing this. Will be part of the next package release.
