### ISSUE TITLE
Ask for name and proof of "other" benefit

### ISSUE THREAD

**Issue by jmadans** [JudicialCouncilOfCalifornia/docassemble.jcc.abilitytopay#27]
If users do not see the public benefit that they are enrolled in, the interview needs to collect the name of the benefit and generate an additional screen asking for proof. 

There are a few paths to doing this within doc assemble, but I think we want for a text field to show when the user hits Other and then use the answer to as the title of the additional proof screen with an attachment.

**Comment by jmadans** [comment]
Rohan - My show if yaml still doesn't show. Can you do this one?

**Comment by rdeshpande** [comment]
@jmadans Why not just have clicking other reveal the file input to upload the document there? Instead of a separate screen? Then they can just specify the name of the document inline.

**Comment by jmadans** [comment]
@rdeshpande It would break the user flow a bit and the file upload field would make that page really long. But the "other " benefit is an edge case so if there's no other way we can fall back on your suggestion

**Comment by rdeshpande** [comment]
Here is a interview block that demonstrates how you could do this:

```
metadata:
  title: Default playground interview
  short title: Test
  comment: This is a learning tool.  Feel free to write over it.
---
mandatory: True
question: |
  Public Benefits
fields:
- 'Are you currently receiving any benefits? If you don''t see the public benefit you are currently enrolled in, click "Other"': benefits
  datatype: checkboxes
  choices:
  - "CalFresh (Food Stamps)": cal_fresh
  - "Medi-Cal": medi_cal
  - "Supplemental Security Income (SSI)": ssi
  - "State Supplemental Payment (SSP)": ssp
  - "County Relief/General Assistance": cr_ga
  - "In Home Supportive Services (IHSS)": ihss
  - "California Work Opportunity and Responsibility to Kids Act (CalWORKS)": cal_works
  - "Tribal Temporary Assistance for Needy Families (TANF)": tanf
  - "Cash Assistance Program for Aged, Blind or Disabled Legal Immigrants (CAPI)": capi
  - Other: other
- "What's the other public benefit you receive?": other_benefit_name
  show if:
    variable: benefits['other']
    is: True
---
question: |
  Upload "${other_benefit_name}" benefits
fields:
- "Upload picture": other_benefit_picture
  datatype: file
---
mandatory: True
code: |
  benefits
  if benefits['other']:
    other_benefit_picture
```

Couple steps here:
1) Use the `show if` syntax I am using, checking for `benefits['other']` being set to True.
2) In the mandatory code block section, condition the other_benefit_picture as being required only if the user has selected benefits['other'].

**Comment by jmadans** [comment]
done!
