### ISSUE TITLE
Only show plea screen for unadjudicated cases

### ISSUE THREAD

**Issue by jmadans** [JudicialCouncilOfCalifornia/docassemble.jcc.abilitytopay#35]
Only show if citation results show an unadjudicated case.

**Comment by jmadans** [comment]
@rdeshpande Akbar has updated the API to include this. Please weigh in with level of effort to only show non-adjudicated cases.

**Comment by rdeshpande** [comment]
This is complete.

**Comment by jmadans** [comment]
Did it, functional!
