### ISSUE TITLE
Data showing in the submission

### ISSUE THREAD

**Issue by jmadans** [JudicialCouncilOfCalifornia/docassemble.jcc.abilitytopay#39]
This what we saw when we submitted: 
<img width="596" alt="screen shot 2019-01-04 at 12 24 43 pm" src="https://user-images.githubusercontent.com/1261618/50709202-daa63d80-101b-11e9-9814-6a794f4a6790.png">

**Comment by rdeshpande** [comment]
Resolved - this was only in the playground.
