### ISSUE TITLE
Error for bad case searches 

### ISSUE THREAD

**Issue by jmadans** [JudicialCouncilOfCalifornia/docassemble.jcc.abilitytopay#43]
System broke when I did an alternative look up with a bad license number.

**Comment by rdeshpande** [comment]
What error text do we want to show? What should the behavior be?

**Comment by jmadans** [comment]
This would be the ideal behaviors: 

Use case #1 : User searches by citation number and the system doesn't return a match, warn the user: "No match was found please check the county and citation number. Try again. Or click 'I don't have my citation to search another way'"

Use case #2: User searches by Name, DL, DOB and doesn't return a match: Check the information you entered. Try again."
