### ISSUE TITLE
Confirm litigant email address with second entry

### ISSUE THREAD

**Issue by Marthaew** [JudicialCouncilOfCalifornia/docassemble.jcc.abilitytopay#45]

**Comment by jmadans** [comment]
@Marthaew Just confirm. You are saying that we want to ask for their email address twice so we can guarantee that they match?

**Comment by Marthaew** [comment]
Shasta asked about this too. We're worried that if they don't enter their email address right, just a small typo, the order will bounce back or will go to wrong place. I don't think we have a system for handling bounce backs? Maybe a "confirm your email address" second entry will minimize that?

**Comment by rdeshpande** [comment]
@jmadans I'm actually not sure how best to do this in DocAssemble, so would be great to ask Jonathan about this first. A confirmation field could be useful for many situations outside of email verification.

**Comment by jmadans** [comment]
This is done! Feel free to test on the testing environment!

**Comment by Marthaew** [comment]
SWEET! Saw it today. Looks great. Makes me feel much more comfortable we'll have fewer order sending errors.
