### ISSUE TITLE
Eligible Case Parameter - $0 due

### ISSUE THREAD

**Issue by Marthaew** [JudicialCouncilOfCalifornia/docassemble.jcc.abilitytopay#57]
The API should have a data point for amount due. If a citation that a litigant enters shows $0 due can we return the same message for other types of ineligible cases?

**Comment by jmadans** [comment]
@Marthaew What's the likelihood of this happening? Can you share more about how this became an issue? Do we feel like users are going to move forward with a request if their citation look up tells them they don't owe any money?

**Comment by Marthaew** [comment]
A court brought it up, just in the vein of not wanting anyone to do extra work. But yes, if they see $0 due right when citation search returns their info, presumably, the will not proceed. We can hold off on this for now and just monitor to see if it's ever an actual issue in use.
