### ISSUE TITLE
Match color for question title to style guide

### ISSUE THREAD

**Issue by jmadans** [JudicialCouncilOfCalifornia/docassemble.jcc.abilitytopay#58]
Somewhere along the way we lost the style guide color in the question title. See images. Wasn't this already in there?
**Style guide:**
<img width="874" alt="screen shot 2019-01-17 at 5 33 23 pm" src="https://user-images.githubusercontent.com/1261618/51360153-5920c780-1a7f-11e9-83c9-7bbdbb3b6344.png">

**Current app:**
<img width="524" alt="screen shot 2019-01-17 at 5 31 36 pm" src="https://user-images.githubusercontent.com/1261618/51360173-72297880-1a7f-11e9-9e7c-9dd54f369e89.png">

**Comment by exygy-dev** [comment]
@slowbot

**Comment by jmadans** [comment]
Fixed.
