### ISSUE TITLE
Cases that check benefits but don't upload a file return an error

### ISSUE THREAD

**Issue by Marthaew** [JudicialCouncilOfCalifornia/docassemble.jcc.abilitytopay#65]
Litigant should be able to enter comment about why they can't upload a file and still continue with request. But error appears at submission

**Comment by Marthaew** [comment]
Issue when using IE as browser

**Comment by jmadans** [comment]
Not uploading a benefit file triggers a submission error within Internet Explorer - even when there has been an explanation.

**Comment by jmadans** [comment]
Suzanne needs to re-test but we believe we got it.

**Comment by jmadans** [comment]
Done
