### ISSUE TITLE
cannot clear browser to start over 

### ISSUE THREAD

**Issue by Marthaew** [JudicialCouncilOfCalifornia/docassemble.jcc.abilitytopay#66]

**Comment by jmadans** [comment]
Is there a function that exists with DA to reset the interview?

**Comment by jmadans** [comment]
Hey, if someone is completing the interview on a public machine and they don't finish it - will their information show up to the next user?

**Comment by jmadans** [comment]
Potential fix is to expire.

**Comment by jmadans** [comment]
We have made a fix so that each session will expire after 60 minutes. Our rationale is that any less time and we could cut off people's actual sessions as they are working through the flow. 
@Marthaew will this suffice for the use case you had in mind about people using this on a public machine?
