### ISSUE TITLE
Add "Start Another Request" Button

### ISSUE THREAD

**Issue by jmadans** [JudicialCouncilOfCalifornia/docassemble.jcc.abilitytopay#84]
Users often have multiple citations that might be eligible for Ability to Pay requests. But they have no way of getting back to the beginning of the interview. 

We need to add a button on the last screen of the interview that allows them to do this. And looks like DA has already got it!
https://docassemble.org/docs/questions.html#special%20buttons

**Comment by bennlich** [comment]
@jmadans You did this, ya?
