### ISSUE TITLE
Set up offsite monitoring for UAT and Prod

### ISSUE THREAD

**Issue by jmadans** [JudicialCouncilOfCalifornia/docassemble.jcc.abilitytopay#87]

**Comment by bennlich** [comment]
Documented in https://github.com/JudicialCouncilOfCalifornia/docassemble.jcc.abilitytopay/commit/320771b49557ee72283f5346fb2266be714422cf. Currently sending e-mails to me and @jmadans if it doesn't find the words "Request a Fine Reduction" on the ability to pay homepages.

**Comment by bennlich** [comment]
Currently configured to check every 5 minutes (shortest time allowed on a free plan).
