### ISSUE TITLE
Add WIC Benefit

### ISSUE THREAD

**Issue by jmadans** [JudicialCouncilOfCalifornia/docassemble.jcc.abilitytopay#88]
We are missing WIC from the current list of benefits. In order to add it, we need to: 
1. Add WIC as a check box option. 
2. Create a proof screen for WIC. 
3. Make sure this information is included in the post request to ATP.

**Comment by bennlich** [comment]
@JCCChris here's the text for the WIC checkbox:
```
WIC: Special Supplemental Nutrition for Women, Infants and Children
```

**Comment by JCCChris** [comment]
Which checkbox should WIC show up after?

**Comment by bennlich** [comment]
Should be after SSI.

```
Checkboxes:
CalFresh (Food Stamps)
Medi-Cal
General Assistance/ County Relief
SSI: Supplemental Security Income
WIC: Special Supplemental Nutrition for Women, Infants and Children
SSP: State Supplemental Payment
IHSS: In Home Supportive Services
CalWORKS: California Work Opportunity and Responsibility to Kids Act
TANF: Temporary Assistance for Needy Families
CAPI: Cash Assistance Program for Aged, Blind or Disabled Legal Immigrants
Other
None of the above
```

**Comment by bennlich** [comment]
Closing this for now. I disabled WIC in these commits until we get support for WIC in the backend:

https://github.com/JudicialCouncilOfCalifornia/docassemble.jcc.abilitytopay/commit/1df5a029ec26826911dac71e445c22fc5634cbb4
https://github.com/JudicialCouncilOfCalifornia/docassemble.jcc.abilitytopay/commit/f579ecd55058afd1e69c3ac0caa38f64e64df475
https://github.com/JudicialCouncilOfCalifornia/docassemble.jcc.abilitytopay/commit/c519d275d6aee6d457dea0e8073d2006844c7e21
