### ISSUE TITLE
Implement Spanish translation

### ISSUE THREAD

**Issue by bennlich** [JudicialCouncilOfCalifornia/docassemble.jcc.abilitytopay#99]
Once we get the Spanish translations for the interview content, we need to implement a feature to switch languages in the interview.

@JCCChris I've more or less mocked up a yaml structure that I think will work in the UAT playground: https://mycitations.uat.courts.ca.gov/playground. The components are:

- a2p-entrypoint.yml
- a2p-en.yml
- a2p-es.yml

See it on the playground here: https://mycitations.uat.courts.ca.gov/interview?i=docassemble.playground1%3Aa2p-entrypoint.yml#page1

I think the remaining tasks are:
1) Pull the code blocks out of a2p-en and a2p-es into a code.yml (so that we don't have to change the logic in both files when we need to make changes.)
2) Insert all the spanish translations into the appropriate places in a2p-es.yml
3) For messages that appear in code.yml, for example errors like [this one](https://github.com/JudicialCouncilOfCalifornia/docassemble.jcc.abilitytopay/blob/master/docassemble/jcc/abilitytopay/data/questions/interview.yml#L67), use a lookup table to get strings in the correct language. I.e. we need a function like `get_e18n_message('ineligible_citation_error', user_language)` that returns the `ineligible_citation_error` text in the appropriate language.

**Comment by JCCChris** [comment]
@bennlich
I've created a translation.yml file and switched interview.yml to use the dictionary lookup.  I think we need to adjust the language selection mechanism still.

**Comment by JCCChris** [comment]
Currently working in Spanish on production.
